### ISSUE TITLE
Adding 10000 to ticks does not add a millisecond. Subtracting 10000 does subtract 1ms from the date.

### ISSUE THREAD

**Issue by mplungjan** [mharen/TicksToDateTime#1]
https://stackoverflow.com/a/77612268/295783

638315425210000000 is 2023-09-29​T00:02:01.000Z plus 10000 
638315425210010000 is 2023-09-29​T00:02:01.000Z is the same according to the site

Whereas

638338147200000000 is 2023-10-25​T07:12:00.000Z minus 10000

638338147199990000 is 2023-10-25​T07:11:59.999Z IS one millisecond less as expected

```
let ticksInMilliseconds = 10000
//to add milliseconds to tick
const startTick = "638315425210000000"; // valid INT in Chrome
console.log("str",startTick,"int",+startTick)
const millisecondsAdded = (+startTick) +  ticksInMilliseconds 
//to reduce one millisecond
const endTick = "638338147200000000"
const millisecondReduced = (+endTick) - ticksInMilliseconds

console.log(startTick,millisecondsAdded)
console.log(endTick,millisecondReduced)
```

**Comment by mharen** [comment]
Thanks for the issue!
